# Generated by Django 2.2.7 on 2019-11-28 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app03', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors_books',
            name='note',
            field=models.CharField(default='nothing', max_length=64, null=True),
        ),
    ]
