# Generated by Django 2.2.7 on 2019-11-27 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='publishinfo',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='bookinfo',
            fields=[
                ('bid', models.AutoField(primary_key=True, serialize=False)),
                ('bname', models.CharField(max_length=32)),
                ('bprice', models.DecimalField(decimal_places=2, default=16.99, max_digits=6)),
                ('binventory', models.IntegerField(default=100)),
                ('bsalesvolume', models.IntegerField(default=0)),
                ('book_pubish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookAPP.publishinfo')),
            ],
        ),
        migrations.CreateModel(
            name='authorinfo',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('aname', models.CharField(max_length=32)),
                ('aage', models.IntegerField(default=20)),
                ('aphone', models.IntegerField(default=4165657767)),
                ('author_book_publish', models.ManyToManyField(to='bookAPP.bookinfo')),
            ],
        ),
    ]
