# Generated by Django 2.2.7 on 2019-12-03 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='authordetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ahobby', models.CharField(default='dog', max_length=32, null=True)),
                ('alocation', models.CharField(default='Canada', max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='publishinfo',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='bookinfo',
            fields=[
                ('bid', models.AutoField(primary_key=True, serialize=False)),
                ('bname', models.CharField(max_length=32)),
                ('bprice', models.DecimalField(decimal_places=2, default=16.99, max_digits=6)),
                ('binventory', models.IntegerField(default=100)),
                ('bsalesvolume', models.IntegerField(default=0)),
                ('btype', models.CharField(default='教育', max_length=32)),
                ('bpublishdata', models.DateField(default='2019-06-16')),
                ('book_pubish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookAPP.publishinfo')),
            ],
        ),
        migrations.CreateModel(
            name='authorinfo',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('aname', models.CharField(max_length=32)),
                ('aage', models.IntegerField(default=20, null=True)),
                ('aphone', models.CharField(max_length=32, null=True)),
                ('adetails', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bookAPP.authordetails')),
                ('author_book_publish', models.ManyToManyField(to='bookAPP.bookinfo')),
            ],
        ),
    ]
