# Generated by Django 2.2.7 on 2019-11-23 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookAPP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookinfo',
            fields=[
                ('bid', models.AutoField(primary_key=True, serialize=False)),
                ('bname', models.CharField(max_length=32)),
                ('book_pubish', models.ForeignKey(on_delete=True, to='bookAPP.publishinfo')),
            ],
        ),
    ]
