# Generated by Django 2.2.7 on 2019-11-27 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookAPP', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='authorinfo',
        ),
    ]
