# Generated by Django 2.2.7 on 2019-11-23 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookAPP', '0002_bookinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfo',
            name='book_pubish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookAPP.publishinfo'),
        ),
        migrations.CreateModel(
            name='authorinfo',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('aname', models.CharField(max_length=32)),
                ('author_book_publish', models.ManyToManyField(to='bookAPP.bookinfo')),
            ],
        ),
    ]
