# Generated by Django 2.2.7 on 2019-11-28 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookAPP', '0002_delete_authorinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='authordetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ahobby', models.CharField(default='dog', max_length=32, null=True)),
                ('alocation', models.CharField(default='Canada', max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='authorinfo',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('aname', models.CharField(max_length=32)),
                ('aage', models.IntegerField(default=20, null=True)),
                ('aphone', models.IntegerField(default=4165657767, null=True)),
                ('adetails', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bookAPP.authordetails')),
                ('author_book_publish', models.ManyToManyField(to='bookAPP.bookinfo')),
            ],
        ),
    ]
