# Generated by Django 2.2.7 on 2019-11-27 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookAPP', '0002_delete_authorinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='authorinfo',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('aname', models.CharField(max_length=32)),
                ('aage', models.IntegerField(default=20)),
                ('aphone', models.IntegerField(default=4165657767)),
                ('author_book_publish', models.ManyToManyField(to='bookAPP.bookinfo')),
            ],
        ),
    ]
