# Generated by Django 2.2.7 on 2019-11-28 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookAPP', '0003_authordetails_authorinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorinfo',
            name='aphone',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
