# Generated by Django 2.2.7 on 2019-11-27 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookAPP', '0003_authorinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='authordetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ahobby', models.CharField(default='dog', max_length=32)),
                ('alocation', models.CharField(default='Canada', max_length=32)),
            ],
        ),
    ]
