# Generated by Django 2.2.7 on 2019-11-28 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookAPP', '0004_auto_20191127_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinfo',
            name='book_pubish',
        ),
        migrations.DeleteModel(
            name='authorinfo',
        ),
        migrations.DeleteModel(
            name='bookinfo',
        ),
    ]
