# Generated by Django 2.2.7 on 2019-11-27 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookAPP', '0004_authordetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorinfo',
            name='adetails',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookAPP.authordetails'),
        ),
    ]
