# Generated by Django 2.2.7 on 2019-11-28 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookAPP', '0005_auto_20191128_1016'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookinfo',
            fields=[
                ('bid', models.AutoField(primary_key=True, serialize=False)),
                ('bname', models.CharField(max_length=32)),
                ('bprice', models.DecimalField(decimal_places=2, default=16.99, max_digits=6)),
                ('binventory', models.IntegerField(default=100)),
                ('bsalesvolume', models.IntegerField(default=0)),
                ('book_pubish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookAPP.publishinfo')),
            ],
        ),
        migrations.CreateModel(
            name='authorinfo',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('aname', models.CharField(max_length=32)),
                ('aage', models.IntegerField(default=20, null=True)),
                ('aphone', models.CharField(max_length=32, null=True)),
                ('adetails', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bookAPP.authordetails')),
                ('author_book_publish', models.ManyToManyField(to='bookAPP.bookinfo')),
            ],
        ),
    ]
