# Generated by Django 2.2.7 on 2019-11-28 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookAPP', '0006_authorinfo_bookinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorinfo',
            name='adetails',
        ),
        migrations.RemoveField(
            model_name='authorinfo',
            name='author_book_publish',
        ),
        migrations.RemoveField(
            model_name='bookinfo',
            name='book_pubish',
        ),
        migrations.DeleteModel(
            name='authordetails',
        ),
        migrations.DeleteModel(
            name='authorinfo',
        ),
        migrations.DeleteModel(
            name='bookinfo',
        ),
        migrations.DeleteModel(
            name='publishinfo',
        ),
    ]
