# Generated by Django 2.2.7 on 2019-11-27 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookAPP', '0007_authordetails_authorinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authordetails',
            name='ahobby',
            field=models.CharField(default='dog', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='authordetails',
            name='alocation',
            field=models.CharField(default='Canada', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='authorinfo',
            name='aage',
            field=models.IntegerField(default=20, null=True),
        ),
        migrations.AlterField(
            model_name='authorinfo',
            name='aphone',
            field=models.IntegerField(default=4165657767, null=True),
        ),
    ]
