# Generated by Django 2.2.7 on 2019-11-28 17:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookAPP', '0008_authordetails_authorinfo_bookinfo_publishinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinfo',
            name='bpublishdata',
            field=models.DateField(default=datetime.date(2019, 11, 28)),
        ),
    ]
