# Generated by Django 2.2.7 on 2019-11-28 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookAPP', '0008_auto_20191127_2350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorinfo',
            name='adetails',
        ),
        migrations.RemoveField(
            model_name='authorinfo',
            name='author_book_publish',
        ),
        migrations.DeleteModel(
            name='authordetails',
        ),
        migrations.DeleteModel(
            name='authorinfo',
        ),
    ]
