# Generated by Django 2.2.7 on 2019-11-28 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookAPP', '0009_bookinfo_bpublishdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinfo',
            name='btype',
            field=models.CharField(default='教育', max_length=32),
        ),
    ]
